server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      enabled: true
      server:
        jdbc:
#          sql: select key, value from properties where application=? and profile=? and label=?
#          sql: SELECT \`KEY\`, \`VALUE\` from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?
#          sql: SELECT KEY, VALUE FROM PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?

          sql: SELECT `KEY`, `VALUE` from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?
  profiles:
    include: database
    active:
      - jdbc
      - local