CREATE TABLE `PROPERTIES` (
      `APPLICATION` VARCHAR(50) NOT NULL DEFAULT 'application',
      `PROFILE` VARCHAR(50) NOT NULL DEFAULT 'default',
      `LABEL` VARCHAR(50) NOT NULL DEFAULT 'master',
      `KEY` VARCHAR(256) NOT NULL,
      `VALUE` VARCHAR(1024) NOT NULL,
      INDEX `UIX_PROPERTIES` (`APPLICATION`, `PROFILE`, `LABEL`, `KEY`) USING BTREE
);